# -*- coding: utf-8 -*-
"""FORECASTING.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kmthkK_9O6x8e4hazUQc-iajTYxoxuaV

## **COVID-19 Total Cases Forecasting per State/UT**
#### **Author:** AKANKSHA MISHRA
##### **Purpose:** Predict next 30 days COVID-19 trends to support policy decisions
"""

import pandas as pd
import matplotlib.pyplot as plt
from prophet import Prophet
import os
import logging

# Suppress Prophet INFO logs
logging.getLogger('prophet').setLevel(logging.ERROR)

"""### **1. Load Dataset**"""

df= pd.read_csv("/content/sample_data/India_COVID19_Statewise_TimeSeries_Analytics_2021.csv")

df.head(2)

print("Columns available:", df.columns)

# Filter only required columns for forecasting
df = df[['Date', 'State_UT', 'Population', 'New_Cases', 'New_Deaths',
         'New_Recoveries', 'Total_Cases', 'Total_Deaths', 'Total_Recoveries', 'Active_Cases']]

"""### **2. Handle Missing Values**"""

df = df.dropna(subset=['Date', 'Total_Cases'])
df['Date'] = pd.to_datetime(df['Date'])

"""###**3. Create output folder**"""

output_dir = "forecasts"
os.makedirs(output_dir, exist_ok=True)

"""### **4. State-wise Forecasting**"""

import logging
logging.getLogger('prophet').setLevel(logging.ERROR)

states = df['State_UT'].unique()
forecast_horizon = 30  # forecast next 30 days

for state in states:
    # Prepare data for Prophet
    state_df = df[df['State_UT'] == state][['Date', 'Total_Cases']].rename(columns={'Date': 'ds', 'Total_Cases': 'y'})

    # Initialize Prophet model
    model = Prophet(daily_seasonality=True)
    model.fit(state_df)

    # Generate future dataframe
    future = model.make_future_dataframe(periods=forecast_horizon)

    # Forecast
    forecast = model.predict(future)

"""### **4. Evaluate Forecast (MAE last 7 days)**"""

if len(state_df) >= 7:
        recent_actual = state_df['y'].iloc[-7:].values
        recent_pred = forecast['yhat'].iloc[-7:].values
        mae = round(abs(recent_actual - recent_pred).mean(), 2)
else:
        mae = "NA"

"""### **5. Visualize Forecast**"""

plt.figure(figsize=(10,5))
plt.plot(state_df['ds'], state_df['y'], label='Actual Total Cases')
plt.plot(forecast['ds'], forecast['yhat'], label='Forecasted Total Cases', linestyle='--')
plt.fill_between(forecast['ds'], forecast['yhat_lower'], forecast['yhat_upper'], color='lightblue', alpha=0.4)
plt.title(f"COVID-19 Total Cases Forecast - {state} | MAE(last 7 days): {mae}")
plt.xlabel("Date")
plt.ylabel("Total Cases")
plt.legend()
plt.tight_layout()
plt.savefig(f"{output_dir}/forecast_{state.replace(' ', '_')}.png")
plt.close()

print(f"Forecast completed for {state} | MAE(last 7 days): {mae}")

print("All state-wise forecasts completed!")